package com.hengaikj.ai.service;
import com.hengaikj.ai.entity.*; import com.hengaikj.ai.mapper.ApiKeyMapper; import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper; import org.springframework.data.redis.core.RedisTemplate; import org.springframework.stereotype.Service; import java.nio.charset.StandardCharsets; import java.security.*; import java.time.Instant; import java.util.*; import java.util.concurrent.TimeUnit;
@Service public class ApiKeyService { private final ApiKeyMapper mapper; private final RedisTemplate<String,Object> redis; public ApiKeyService(ApiKeyMapper m,RedisTemplate<String,Object> r){mapper=m;redis=r;}
 public ApiKeyCreateResponse create(long enterprise,long project,ApiKeyCreateRequest req){if(req.keyName()==null||req.keyName().isBlank())throw new IllegalArgumentException("keyName不能为空");byte[] raw=new byte[32];new SecureRandom().nextBytes(raw);String secret="ha_"+Base64.getUrlEncoder().withoutPadding().encodeToString(raw);ApiKeyEntity e=new ApiKeyEntity();e.enterpriseId=enterprise;e.projectId=project;e.keyName=req.keyName();e.keyPrefix=secret.substring(0,8);e.keyHash=hash(secret).getBytes(StandardCharsets.UTF_8);e.status="ENABLED";e.expiresAt=req.expiresAt();e.createdAt=Instant.now();mapper.insert(e);cache(e,secret);return new ApiKeyCreateResponse(e.id,e.keyName,e.keyPrefix,e.status,e.expiresAt,e.createdAt,secret);}
 public List<ApiKeySummary> list(long enterprise,long project){return mapper.selectList(new QueryWrapper<ApiKeyEntity>().eq("enterprise_id",enterprise).eq("project_id",project)).stream().map(e->new ApiKeySummary(e.id,e.keyName,e.keyPrefix,e.status,e.expiresAt,e.createdAt)).toList();}
 public ApiKeySummary change(long enterprise,long project,long id,String status){ApiKeyEntity e=mapper.selectOne(new QueryWrapper<ApiKeyEntity>().eq("id",id).eq("enterprise_id",enterprise).eq("project_id",project));if(e==null)throw new NoSuchElementException("API Key不存在");if("REVOKED".equals(e.status)&&!"REVOKED".equals(status))throw new IllegalStateException("已撤销密钥不可恢复");e.status=status;mapper.updateById(e);return new ApiKeySummary(e.id,e.keyName,e.keyPrefix,e.status,e.expiresAt,e.createdAt);}
 private void cache(ApiKeyEntity e,String secret){redis.opsForValue().set("ha:dev:apikey:"+hash(secret),e,5,TimeUnit.MINUTES);}
 public ApiKeyEntity findActive(String secret,long enterpriseId,long projectId){String hash=hash(secret);Object cached=redis.opsForValue().get("ha:dev:apikey:"+hash);ApiKeyEntity e=cached instanceof ApiKeyEntity?(ApiKeyEntity)cached:null;if(e==null)e=mapper.selectOne(new QueryWrapper<ApiKeyEntity>().eq("key_hash",hash.getBytes(StandardCharsets.UTF_8)).eq("enterprise_id",enterpriseId).eq("project_id",projectId));if(e==null||!"ENABLED".equals(e.status)||(e.expiresAt!=null&&e.expiresAt.isBefore(Instant.now())))return null;return e;}
 public static String hash(String s){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
}
